name: "Tests"

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - name: "Set up node"
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: "Continuous integration checks"
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
          yarn run build --if-present
          yarn test