name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v1
      - name: "Set up node"
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - uses: actions/cache@v1
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies from cache
        run: |
          rm -rf node_modules && yarn install --prefer-offline --frozen-lockfile
          
      - name: Install dependencies from repository
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile

      - name: "Run tests"
        run: |
          yarn run build --if-present
          yarn test
