name: release

on:
  workflow_dispatch


jobs:
  release:
    runs-on: "ubuntu-latest"
    needs: commit_commented
        
    steps:
      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
