name: release

on:
  issue_comment:
    types:
      - edited

jobs:
  commit_commented:
    name: Commit comment
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo github event: ${{ github.event.type }}
  
  release:
    runs-on: "ubuntu-latest"
    needs: commit_commented
        
    steps:
      - name: Create Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          